version: '3'

services:
  db:
    image: postgis/postgis
    env_file:
      - ./.envs/.postgres
    volumes:
      - cynr-data:/var/lib/postgresql/data
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.envs/.postgres
      - ./.envs/.cynr_app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  cynr-data: