# Generated by Django 3.1.2 on 2020-10-13 23:44

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestadoresServicios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('razon_social', models.TextField(default=None)),
                ('presentacion', models.TextField(blank=True, default=None)),
                ('logo', models.ImageField(upload_to='cynr_app/logos')),
                ('ubicacion', models.TextField(default=None)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prestadores_servicios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organismos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('razon_social', models.TextField(default=None)),
                ('presentacion', models.TextField(blank=True, default=None)),
                ('logo', models.ImageField(upload_to='cynr_app/logos')),
                ('ubicacion', models.TextField(default=None)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organismos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('obs', models.JSONField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'observaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ObrasToma',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(default=None)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('tipo', models.TextField(choices=[('ESTACION FIJA', 'ESTACIÓN DE BOMBEO  CON BATERIA DE BOMBAS DE COTA FIJA'), ('PONTON', 'PONTÓN : ESTACIÓN DE BOMBEO  CON BATERIA DE BOMBAS DE COTA VARIABLE SEGÚN NA')])),
                ('servicio', models.TextField(choices=[('PERMANTENTE', 'PERMENENTE: Obra que presta un servicio permanente.'), ('TRANSITORIA', 'TRANSITORIA: Obra que presta un servicio temporalmente.')])),
                ('uso', models.TextField(choices=[('CONSUMO', 'CONSUMO'), ('INDUSTRIAL', 'INDUSTRIAL'), ('RIEGO', 'RIEGO')])),
                ('estado', models.TextField(choices=[('FUNCIONAMIENTO PLENO', 'FUNCIONAMIENTO PLENO: Funcionamiento sin limitaciones'), ('FUNCIONAMIENTO PARCIAL', 'FUNCIONAMIENTO PARCIAL: Funcionamiento con limitaciones '), ('INACTIVA', 'INACTIVA: Desafectada del Sevicio')])),
                ('cynr', django.contrib.postgres.fields.hstore.HStoreField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_presserv', models.ForeignKey(blank=True, db_column='id_presserv', on_delete=django.db.models.deletion.CASCADE, related_name='idPresServObra', to='cynr_app.prestadoresservicios')),
            ],
            options={
                'db_table': 'obras_toma',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entrevistas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entrevista', models.JSONField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entrevistas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_org', models.ForeignKey(blank=True, db_column='id_org', on_delete=django.db.models.deletion.CASCADE, related_name='idOrgContacto', to='cynr_app.prestadoresservicios')),
                ('id_presserv', models.ForeignKey(blank=True, db_column='id_presserv', on_delete=django.db.models.deletion.CASCADE, related_name='idPresServContacto', to='cynr_app.prestadoresservicios')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contactos',
                'managed': True,
            },
        ),
    ]
