# Generated by Django 3.1.2 on 2020-11-07 18:41

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(default=None, max_length=50, verbose_name='Categoria')),
                ('nombre', models.CharField(default=None, max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default=None, verbose_name='Descripción')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, srid=4326, verbose_name='Georreferenciación')),
                ('ficha_tec', models.FileField(blank=True, upload_to='fichas_tecnicas/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'infraestructura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=200, verbose_name='Nombre')),
                ('categoria', models.CharField(default=None, max_length=50)),
                ('presentacion', models.TextField(blank=True, default=None, verbose_name='Presentación')),
                ('pag_web', models.URLField(blank=True, verbose_name='Página Web')),
                ('logo', models.ImageField(blank=True, upload_to='cynr_app/logos', verbose_name='Logo')),
                ('direccion', models.CharField(default=None, max_length=200, verbose_name='Dirección')),
                ('tel', models.CharField(default=None, max_length=50, verbose_name='Teléfono')),
                ('jurisdiccion', models.CharField(default=None, max_length=200, verbose_name='Jurisdicción')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instituciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ObrasToma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo')),
                ('funcionamiento', models.CharField(max_length=200, verbose_name='Funcionamiento')),
                ('uso', models.CharField(max_length=200, verbose_name='Uso')),
                ('estado', models.CharField(max_length=200, verbose_name='Estado')),
                ('desc_estado', models.TextField(blank=True, default=None, verbose_name='Descripción Estado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_infra', models.ForeignKey(db_column='id_infra', on_delete=django.db.models.deletion.CASCADE, related_name='idInfra', to='cynr_app.infraestructura')),
            ],
            options={
                'db_table': 'obras_toma',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encabezado', models.CharField(default=None, max_length=200, verbose_name='Encabezado')),
                ('presentacion', models.TextField(blank=True, default=None, verbose_name='Presentación')),
                ('fecha_hora', models.DateTimeField(blank=True)),
                ('link_not', models.URLField(blank=True, verbose_name='Link Noticia')),
                ('arch_not', models.FileField(blank=True, max_length=200, upload_to='cynr_app/noticias', verbose_name='Archivo Noticia')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_inst', models.ForeignKey(blank=True, db_column='id_inst', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idNotInstitucion', to='cynr_app.instituciones')),
            ],
        ),
        migrations.AddField(
            model_name='infraestructura',
            name='id_inst',
            field=models.ForeignKey(blank=True, db_column='id_inst', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idInfInstitucion', to='cynr_app.instituciones'),
        ),
        migrations.CreateModel(
            name='GruposCategorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.TextField(verbose_name='Grupo Categoría')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grupos_categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.TextField(default=None)),
                ('titulo', models.TextField(default=None)),
                ('descripcion', models.TextField(blank=True, default=None)),
                ('documento', models.JSONField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_cynr', models.ForeignKey(db_column='id_cynr', on_delete=django.db.models.deletion.CASCADE, related_name='idCyNRDoc', to='cynr_app.infraestructura')),
                ('id_infra', models.ForeignKey(db_column='id_infra', on_delete=django.db.models.deletion.CASCADE, related_name='idInfraDoc', to='cynr_app.infraestructura')),
            ],
            options={
                'db_table': 'documentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocInstitucionales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=200, verbose_name='Nombre')),
                ('presentacion', models.TextField(blank=True, default=None, verbose_name='Presentación')),
                ('categoria', models.CharField(default=None, max_length=50, verbose_name='Categoria')),
                ('link_doc', models.URLField(blank=True, verbose_name='Link Documento')),
                ('arch_doc', models.FileField(blank=True, max_length=200, upload_to='cynr_app/doc_instituciones', verbose_name='Archivo')),
                ('jurisdiccion', models.CharField(default=None, max_length=200, verbose_name='Jurisdicción')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc_institucionales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CyNR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unid_meteo_est', models.IntegerField(blank=True, verbose_name='Estación SIyAH')),
                ('referencia', models.TextField(verbose_name='Referencia')),
                ('valor', models.FloatField()),
                ('descripcion', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_infra', models.ForeignKey(db_column='id_infra', on_delete=django.db.models.deletion.CASCADE, related_name='idInfraCyN', to='cynr_app.infraestructura')),
            ],
            options={
                'db_table': 'cynr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, default=None, max_length=200, verbose_name='Cargo')),
                ('dir_inst', models.CharField(blank=True, default=None, max_length=200, verbose_name='Dirección Institucional')),
                ('tel_inst', models.CharField(blank=True, default=None, max_length=50, verbose_name='Teléfono Institucional')),
                ('email_inst', models.CharField(blank=True, default=None, max_length=50, verbose_name='Email Institucional')),
                ('id_inst', models.ForeignKey(db_column='id_inst', on_delete=django.db.models.deletion.CASCADE, related_name='idContInstitucion', to='cynr_app.instituciones')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contactos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.TextField(verbose_name='Categoría')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='idGruposCategorias', to='cynr_app.gruposcategorias')),
            ],
            options={
                'db_table': 'categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.TextField(default=None)),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'archivos',
                'managed': True,
            },
        ),
    ]
# DEBERIAMOS INSERTAR CATEGORIAS INICIALES, SI NO SE GENERA UN ERROR