# Generated by Django 3.1.2 on 2020-11-25 20:06

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, default=None, max_length=200, verbose_name='Cargo')),
                ('dir_inst', models.CharField(blank=True, default=None, max_length=200, verbose_name='Dirección Institucional')),
                ('tel_inst', models.CharField(blank=True, default=None, max_length=50, verbose_name='Teléfono Institucional')),
                ('email_inst', models.EmailField(blank=True, default=None, max_length=254, verbose_name='Email Institucional')),
            ],
            options={
                'db_table': 'contactos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.TextField(default=None)),
                ('titulo', models.TextField(default=None)),
                ('descripcion', models.TextField(blank=True, default=None)),
                ('fecha_hora', models.DateTimeField()),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_contacto', models.ForeignKey(blank=True, db_column='id_contacto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idContDoc', to='cynr_app.contactos', verbose_name='Entrevistado')),
            ],
            options={
                'db_table': 'documentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(default=None, max_length=50, verbose_name='Categoria')),
                ('nombre', models.CharField(default=None, max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default=None, verbose_name='Descripción')),
                ('geom', django.contrib.gis.db.models.fields.GeometryCollectionField(null=True, srid=4326, verbose_name='Georreferenciación')),
                ('ficha_tec', models.FileField(blank=True, upload_to='fichas_tecnicas/')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'infraestructura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=200, verbose_name='Nombre')),
                ('categoria', models.CharField(default=None, max_length=50)),
                ('presentacion', models.TextField(blank=True, default=None, verbose_name='Presentación')),
                ('pag_web', models.URLField(blank=True, verbose_name='Página Web')),
                ('logo', models.ImageField(blank=True, upload_to='cynr_app/logos', verbose_name='Logo')),
                ('direccion', models.CharField(default=None, max_length=200, verbose_name='Dirección')),
                ('tel', models.CharField(default=None, max_length=50, verbose_name='Teléfono')),
                ('alc_geografico', models.CharField(default=None, max_length=200, verbose_name='Alcance Geográfico')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instituciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ObrasToma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo')),
                ('funcionamiento', models.CharField(max_length=200, verbose_name='Funcionamiento')),
                ('uso', models.CharField(max_length=200, verbose_name='Uso')),
                ('estado', models.CharField(max_length=200, verbose_name='Estado')),
                ('desc_estado', models.TextField(blank=True, default=None, verbose_name='Descripción Estado')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_infra', models.ForeignKey(db_column='id_infra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idObrTomaInfra', to='cynr_app.infraestructura')),
            ],
            options={
                'db_table': 'obras_toma',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encabezado', models.CharField(default=None, max_length=200, verbose_name='Encabezado')),
                ('presentacion', models.TextField(blank=True, default=None, verbose_name='Presentación')),
                ('fecha_hora', models.DateTimeField()),
                ('link_not', models.URLField(blank=True, verbose_name='Link Noticia')),
                ('arch_not', models.FileField(blank=True, max_length=200, upload_to='cynr_app/noticias', verbose_name='Archivo Noticia')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_infra', models.ForeignKey(blank=True, db_column='id_infra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idNotInfra', to='cynr_app.infraestructura', verbose_name='Infraestructura')),
                ('id_inst', models.ForeignKey(blank=True, db_column='id_inst', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idNotInstitucion', to='cynr_app.instituciones', verbose_name='Institución')),
            ],
            options={
                'db_table': 'noticias',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='infraestructura',
            name='id_inst',
            field=models.ForeignKey(blank=True, db_column='id_inst', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idInfInstitucion', to='cynr_app.instituciones'),
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.TextField(default=None)),
                ('descripcion', models.TextField(default=None)),
                ('ilustracion', models.BooleanField(verbose_name='Ilustra Documento')),
                ('imagen', models.FileField(upload_to='imagenes/')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_cont', models.ForeignKey(db_column='id_cont', on_delete=django.db.models.deletion.CASCADE, related_name='idContImg', to='cynr_app.documentos', verbose_name='Archivo')),
            ],
            options={
                'db_table': 'imagenes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GruposCategorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.TextField(verbose_name='Grupo Categoría')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grupos_categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocInstitucionales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=200, verbose_name='Nombre')),
                ('presentacion', models.TextField(blank=True, default=None, verbose_name='Presentación')),
                ('categoria', models.CharField(default=None, max_length=50, verbose_name='Categoria')),
                ('link_doc', models.URLField(blank=True, verbose_name='Link Documento')),
                ('arch_doc', models.FileField(blank=True, max_length=200, upload_to='cynr_app/doc_instituciones', verbose_name='Archivo')),
                ('alc_geografico', models.CharField(default=None, max_length=200, verbose_name='Alcance Geográfico')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_inst', models.ForeignKey(db_column='id_inst', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idDocInstitucion', to='cynr_app.instituciones')),
            ],
            options={
                'db_table': 'doc_institucionales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CyNR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unid_meteo_est', models.IntegerField(blank=True, null=True, verbose_name='Estación SIyAH')),
                ('referencia', models.TextField(verbose_name='Referencia')),
                ('valor', models.FloatField(null=True)),
                ('descripcion', models.TextField()),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_infra', models.ForeignKey(db_column='id_infra', on_delete=django.db.models.deletion.CASCADE, related_name='idInfraCyN', to='cynr_app.infraestructura')),
            ],
            options={
                'db_table': 'cynr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContDocumentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(default=None)),
                ('contenido', models.TextField(default=None, verbose_name='Contenido')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_cynr', models.ForeignKey(blank=True, db_column='id_cynr', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idCyNRDocCont', to='cynr_app.cynr', verbose_name='Cota o Nivel')),
                ('id_doc', models.ForeignKey(db_column='id_doc', on_delete=django.db.models.deletion.CASCADE, related_name='idContDoc', to='cynr_app.documentos', verbose_name='Documento')),
                ('id_infra', models.ForeignKey(blank=True, db_column='id_infra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idInfraDocCont', to='cynr_app.infraestructura', verbose_name='Infraestructura')),
            ],
            options={
                'db_table': 'cont_documentos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='contactos',
            name='id_inst',
            field=models.ForeignKey(db_column='id_inst', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idContInstitucion', to='cynr_app.instituciones'),
        ),
        migrations.AddField(
            model_name='contactos',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.TextField(verbose_name='Categoría')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='idGruposCategorias', to='cynr_app.gruposcategorias')),
            ],
            options={
                'db_table': 'categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.TextField(default=None)),
                ('descripcion', models.TextField(default=None)),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_cont', models.ForeignKey(db_column='id_cont', on_delete=django.db.models.deletion.CASCADE, related_name='idContArch', to='cynr_app.documentos', verbose_name='Archivo')),
            ],
            options={
                'db_table': 'archivos',
                'managed': True,
            },
        ),
    ]
