# Generated by Django 3.1.2 on 2020-11-07 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='id_cynr',
            field=models.ForeignKey(db_column='id_cynr', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idCyNRDoc', to='cynr_app.infraestructura'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='id_infra',
            field=models.ForeignKey(db_column='id_infra', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idInfraDoc', to='cynr_app.infraestructura'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
