# Generated by Django 3.1.7 on 2021-03-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituciones',
            name='direccion',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='instituciones',
            name='logo',
            field=models.ImageField(blank=True, default='logos_defecto/instituciones.jpg', upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='instituciones',
            name='tel',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Teléfono'),
        ),
    ]
