# Generated by Django 2.1.5 on 2021-01-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0002_auto_20201228_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraestructura',
            name='ficha_tec',
            field=models.FileField(blank=True, upload_to='cynr_app/fichas_tecnicas/'),
        ),
        migrations.AlterField(
            model_name='instituciones',
            name='logo',
            field=models.ImageField(blank=True, upload_to='cynr_app/logos/', verbose_name='Logo'),
        ),
    ]
