# Generated by Django 3.1.2 on 2020-10-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0002_auto_20201026_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gruposcategorias',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
