# Generated by Django 3.1.7 on 2021-03-31 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cynr_app', '0002_auto_20210305_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docinstitucionales',
            name='arch_doc',
            field=models.FileField(blank=True, max_length=250, upload_to='doc_instituciones/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='docinstitucionales',
            name='id_inst',
            field=models.ForeignKey(blank=True, db_column='id_inst', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idDocInstitucion', to='cynr_app.instituciones', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='ficha_tec',
            field=models.FileField(blank=True, upload_to='fichas_tecnicas/', verbose_name='Ficha Técnica'),
        ),
        migrations.CreateModel(
            name='AtributosPorDefectoInfra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributos', models.JSONField()),
                ('autor_id', models.ForeignKey(db_column='autor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, related_name='idCategoria', to='cynr_app.categorias')),
            ],
        ),
    ]
