# Generated by Django 3.1.2 on 2020-11-09 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0002_auto_20201107_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='docinstitucionales',
            name='id_inst',
            field=models.ForeignKey(db_column='id_inst', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idDocInstitucion', to='cynr_app.instituciones'),
        ),
    ]
