# Generated by Django 3.1.2 on 2020-11-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0003_docinstitucionales_id_inst'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticias',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='noticias',
            table='noticias',
        ),
    ]
