# Generated by Django 3.1.2 on 2020-10-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0003_auto_20201026_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cynr',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docinstituciones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instituciones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='obrastoma',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
