# Generated by Django 3.1.2 on 2020-11-10 14:44

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cynr_app', '0004_auto_20201109_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326, verbose_name='Georreferenciación'),
        ),
    ]
