# Generated by Django 3.0.7 on 2021-01-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0004_carrusel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrusel',
            name='leer_mas_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link Leer Más'),
        ),
    ]
