# Generated by Django 3.1.2 on 2020-10-26 21:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0004_auto_20201026_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraestructura',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
