# Generated by Django 3.1.2 on 2020-11-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0005_auto_20201026_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituciones',
            name='direccion',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instituciones',
            name='jurisdiccion',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instituciones',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cynr_app/logos'),
        ),
        migrations.AlterField(
            model_name='instituciones',
            name='pag_web',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instituciones',
            name='presentacion',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instituciones',
            name='tel',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
