# Generated by Django 3.1.2 on 2020-11-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0005_auto_20201110_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cynr',
            name='unid_meteo_est',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estación SIyAH'),
        ),
        migrations.AlterField(
            model_name='obrastoma',
            name='id_infra',
            field=models.ForeignKey(db_column='id_infra', on_delete=django.db.models.deletion.CASCADE, related_name='idObrTomaInfra', to='cynr_app.infraestructura'),
        ),
    ]
