# Generated by Django 3.1.7 on 2021-04-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0005_infraestructura_id_atr_def'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributospordefectoinfra',
            name='atributos',
            field=models.JSONField(verbose_name='Atributos'),
        ),
    ]
