# Generated by Django 2.1.5 on 2021-01-18 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0005_carrusel_leer_mas_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
