# Generated by Django 3.2 on 2021-05-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0006_auto_20210406_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capasgeojson',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='capasgeojson',
            table='capasgeojson',
        ),
    ]
