# Generated by Django 3.1.2 on 2020-11-19 20:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0007_auto_20201117_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraestructura',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(null=True, srid=4326, verbose_name='Georreferenciación'),
        ),
    ]
