# Generated by Django 3.2 on 2021-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0007_auto_20210527_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='capasgeojson',
            name='arch_capa',
            field=models.FileField(blank=True, max_length=200, upload_to='cynr_app/capasgeojson', verbose_name='Archivo de Capa'),
        ),
        migrations.AlterField(
            model_name='capasgeojson',
            name='capa',
            field=models.JSONField(blank=True),
        ),
    ]
