# Generated by Django 2.1.5 on 2021-01-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0007_auto_20210118_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='apellido',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='contactos',
            name='email_particular',
            field=models.EmailField(blank=True, default=None, max_length=254, verbose_name='Email Particular'),
        ),
        migrations.AddField(
            model_name='contactos',
            name='institucion_no_reg',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='Institución no Registrada'),
        ),
        migrations.AddField(
            model_name='contactos',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='contactos',
            name='tel_particular',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='Telefono Paricular'),
        ),
    ]
