# Generated by Django 3.2 on 2021-05-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0008_auto_20210528_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capasgeojson',
            name='capa',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
