# Generated by Django 3.1.2 on 2020-11-19 21:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0008_auto_20201119_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraestructura',
            name='geom2',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(null=True, srid=4326, verbose_name='Georreferenciación Coleccion'),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326, verbose_name='Georreferenciación'),
        ),
    ]
