# Generated by Django 3.2 on 2021-05-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0009_alter_capasgeojson_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capasgeojson',
            name='arch_capa',
            field=models.FileField(max_length=200, upload_to='capasgeojson/', verbose_name='Archivo de Capa'),
        ),
        migrations.RemoveField(
            model_name='docinstitucionales',
            name='id_inst',
        ),
        migrations.AddField(
            model_name='docinstitucionales',
            name='id_inst',
            field=models.ManyToManyField(blank=True, db_column='id_inst', default=None, null=True, related_name='idDocInstitucion', to='cynr_app.Instituciones', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='arch_not',
            field=models.FileField(blank=True, max_length=200, upload_to='noticias/', verbose_name='Archivo Noticia'),
        ),
    ]
