# Generated by Django 3.2 on 2021-05-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0010_auto_20210528_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docinstitucionales',
            name='id_inst',
            field=models.ManyToManyField(db_column='id_inst', default=None, related_name='idDocInstitucion', to='cynr_app.Instituciones', verbose_name='Institución'),
        ),
    ]
