# Generated by Django 3.2 on 2021-05-31 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0011_alter_docinstitucionales_id_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='id_fuente',
            field=models.ForeignKey(blank=True, db_column='id_fuente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idNotFuente', to='cynr_app.instituciones', verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='docinstitucionales',
            name='id_inst',
            field=models.ManyToManyField(blank=True, db_column='id_inst', default=None, related_name='idDocInstitucion', to='cynr_app.Instituciones', verbose_name='Institución'),
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='id_infra',
        ),
        migrations.AddField(
            model_name='noticias',
            name='id_infra',
            field=models.ManyToManyField(blank=True, db_column='id_inst', default=None, related_name='idNotInfra', to='cynr_app.Infraestructura', verbose_name='Infraestructura'),
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='id_inst',
        ),
        migrations.AddField(
            model_name='noticias',
            name='id_inst',
            field=models.ManyToManyField(blank=True, db_column='id_inst', default=None, related_name='idNotInstitucion', to='cynr_app.Instituciones', verbose_name='Institución'),
        ),
    ]
