# Generated by Django 3.2 on 2021-05-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cynr_app', '0013_auto_20210531_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='id_infra',
            field=models.ManyToManyField(blank=True, default=None, related_name='idNotInfra', to='cynr_app.Infraestructura'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='id_inst',
            field=models.ManyToManyField(blank=True, default=None, related_name='idNotInstitucion', to='cynr_app.Instituciones'),
        ),
    ]
