"""
Django settings for cynr_aplicacion project.

Generated by 'django-admin startproject' using Django 3.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$m_k+k34ezas=rh4xs_8leum@c-0_qzkq$0+#17l%3!(f80042'
#SECRET_KEY = os.environ['SECRET_KEY']
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = os.environ['DEBUG']

ALLOWED_HOSTS = ['0.0.0.0','localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django.contrib.postgres',
     'cynr_app.apps.CynrAppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cynr_aplicacion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media'
            ],
        },
    },
]

WSGI_APPLICATION = 'cynr_aplicacion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
         'ENGINE': 'django.contrib.gis.db.backends.postgis',
         'NAME':'cynr',
         'USER':'cynr',
        'PASSWORD':'navidad',}
    #'default': {
    #    'ENGINE': 'django.contrib.gis.db.backends.postgis',
    #    'NAME': os.environ['POSTGRES_DB'],
    #    'USER': os.environ['POSTGRES_USER'],
    #    'PASSWORD': os.environ['POSTGRES_PASSWORD'],
    #    'HOST': os.environ['POSTGRES_HOST'],
    #    'PORT': os.environ['POSTGRES_PORT'],
    #          }
}

# Superusuario
#DJANGO_SUPERUSER_USERNAME=os.environ['DJANGO_SUPERUSER_USERNAME']
#DJANGO_SUPERUSER_EMAIL=os.environ['DJANGO_SUPERUSER_EMAIL']
#DJANGO_SUPERUSER_PASSWORD=os.environ['DJANGO_SUPERUSER_PASSWORD']

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL =  'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# REGISTRACION Y AUTENTICACION
LOGIN_REDIRECT_URL = 'cynr_app:index'
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL	= 'cynr_app:index'
# ES NECESARIO CONFIGURAR LA LIBRERIA DE GDAL A USAR
#GDAL_LIBRARY_PATH = "c:\\users\\juanp\\onedrive\\ina\proyecto_cynr\\cynrvenv\\lib\\site-packages"